---
- name: restart nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart php-fpm
  systemd:
    name: php{{php_version}}-fpm
    state: restarted

- name: restart monit
  systemd:
    name: monit
    daemon_reload: yes
    state: restarted

- name: start monit
  systemd:
    name: monit
    daemon_reload: yes
    state: started
