---
# install-password-pusher and patch

- name: clone the password pusher repository
  git:
    repo: "{{auto_provision_pwpusher_git}}"
    dest: /var/www/pwpusher
    recursive: yes
    version: "{{ auto_provision_pwpusher_version }}"
    accept_hostkey: yes
    force: yes
  tags:
    - pwpusher

- name: nginx sites-available for password pusher
  template:
    src: "{{files}}/etc/nginx/sites-available/pwpusher.j2"
    dest: /etc/nginx/sites-available/pwpusher
    mode: '0644'
    owner: root
    group: root
  tags:
    - pwpusher

- name: copy patch for pwpusher to work with eqpress
  copy:
    src: "{{files}}/var/www/pwpusher/pw_eqpress.patch"
    dest: /var/www/pwpusher/pw_eqpress.patch
  tags:
    - pwpusher

- name: patch pwpusher 
  shell: "cd /var/www/pwpusher && /usr/bin/git checkout -- . && /usr/bin/git apply pw_eqpress.patch"
  tags:
    - pwpusher

- name: install pwpusher custom config file
  template:
    src: "{{files}}/var/www/pwpusher/config.php.j2"
    dest: /var/www/pwpusher/pwpusher_private/config.php
    owner: root
    group: root
    mode: '0644'
  tags:
    - pwpusher

- name: install pwpusher custom install file
  template:
    src: "{{files}}/var/www/pwpusher/install.php.j2"
    dest: /var/www/pwpusher/eq_pwinstall.php
    owner: root
    group: root
    mode: '0700'
  tags:
    - pwpusher

- name: run pwpusher custom install script
  shell: cd /var/www/pwpusher && /usr/bin/php eq_pwinstall.php
  tags:
    - pwpusher

- name: remove some files
  file:
    path: "/var/www/pwpusher/{{ item }}"
    state: absent
  loop:
    - install.php
    - eq_pwinstall.php
    - pw_eqpress.patch
  tags:
    - pwpusher

- name: link password pusher nginx config 
  file:
    src: /etc/nginx/sites-available/pwpusher
    dest: /etc/nginx/sites-enabled/pwpusher
    state: link
  tags:
    - pwpusher
