---
# file: roles/deploy-auto-provision-code/tasks/main.yml
#
- name: deploy provision scripts
  synchronize:
    src: "{{ files }}/var/www/eqpress-www/provision/"
    dest: "{{ auto_provision_base_directory }}/"
    mode: push
    checksum: true
    rsync_opts:
      - '--exclude=*.j2'
      - '--chown=www-data:www-data'
  tags:
    - provision

- name: deploy main code from template
  template:
    src: "{{ files }}/var/www/eqpress-www/provision/ep-provision.php.j2"
    dest: "{{ auto_provision_base_directory }}/ep-provision.php"
    mode: '0644'
    owner: www-data
    group: www-data

- name: deploy util code from template
  template:
    src: "{{ files }}/var/www/eqpress-www/provision/includes/class-ep-provision-util.php.j2"
    dest: "{{ auto_provision_base_directory }}/includes/class-ep-provision-util.php"
    mode: '0644'
    owner: www-data
    group: www-data

- name: deploy monit script
  template:
    src: "{{ files }}/usr/local/sbin/monit_ep_provision.sh.j2"
    dest: /usr/local/sbin/monit_ep_provision.sh
    mode: '0750'
    owner: root
    group: staff
  tags:
    - provision

- name: deploy ansible hosts file
  template:
    src: "{{ files }}/etc/ansible/hosts.j2"
    dest: /etc/ansible/hosts
    mode: '0644'
    owner: root
    group: staff
  tags:
    - provision
