---
- name: Install nagios packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nagios-nrpe-server
    - nagios-plugins-common
    - nagios-plugins-basic
  tags:
    - nagios

- name: Install scripts to all
  template:
    src: "{{item}}.j2"
    dest: "/usr/local/bin/{{item}}"
    owner: root
    group: staff
    mode: '0755'
  with_items:
    - runargs.sh
    - check_big_files.sh
    - check_connections.sh
    - check_freememory.sh
    - check_ifutil.pl
    - check_tcptraffic
  tags:
    - nagios

- name: Install scripts to slave
  template:
    src: "{{item}}.j2"
    dest: "/usr/local/bin/{{item}}"
    owner: root
    group: staff
    mode: '0755'
  when: mysql_repl_role is defined and mysql_repl_role == 'slave' and mysql_repl_master is defined
  with_items:
    - check_backup_from_master.sh
  tags:
    - nagios

- name: create args directory for nagios nrpe args files
  file:
    path: /etc/nagios/args
    owner: root
    group: root
    mode: '0755'
    state: directory
  tags:
    - nagios

- name: Install args files
  template:
    src: "etc/args/{{item}}.j2"
    dest: "/etc/nagios/args/{{item}}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - check_big_files.sh.args
    - check_connections.sh.args
    - check_disk.args
    - check_freememory.sh.args
    - check_ifutil.pl.args
    - check_load.args
    - check_procs.args
    - check_swap.args
    - check_users.args
    - check_zombies.args
  tags:
    - nagios

- name: Install args slave only
  template:
    src: "etc/args/{{item}}.j2"
    dest: "/etc/nagios/args/{{item}}"
    owner: root
    group: root
    mode: '0644'
  when: mysql_repl_role is defined and mysql_repl_role == 'slave' and mysql_repl_master is defined
  with_items:
    - check_backup_from_master.sh.args
  tags:
    - nagios

- name: Install nrpe config files
  template:
    src: "etc/{{item}}.j2"
    dest: "/etc/nagios/{{item}}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - nrpe.cfg
    - nrpe_local.cfg
  notify:
    - 'restart nrpe'
  tags:
    - nagios

# TODO: Need to make this smarter and only run if needed so it does not
# insert duplicate rules
- name: add firewall rule to allow nagios server to connect
  command: /sbin/iptables -I INPUT -s {{item}} -p tcp -m state --state NEW --dport 5666 -j ACCEPT
  with_items:
    - "{{ nagios_server_ips.split(',') }}"
  tags:
    - nagios
    - security
    - firewall

- name: save new firewall rule
  shell: /sbin/iptables-save > /etc/iptables.up.rules
  tags:
    - nagios
    - security
    - firewall

# Still needed
# defaults for args templates
