---
- hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: "auto_provision_db_host"
      prompt: "Auto-provision database host"
      default: "localhost"
      private: no
    
    - name: "auto_provision_base_directory"
      prompt: "Auto-provision base directory"
      default: "/var/www/easypress.ca/provision"
      private: no

    - name: "auto_provision_log_file"
      prompt: "Auto-provision log file name (relative to base directory)"
      default: "ep-provision.log"
      private: no

    - name: "auto_provision_db_charset"
      prompt: "Auto-provision default database character set"
      default: "utf8"
      private: no

    - name: "auto_provision_db_collate"
      prompt: "Auto-provision default database collation"
      default: "utf8_unicode_ci"
      private: no

    - name: "auto_provision_dev_rand"
      prompt: "Auto-provison random number device"
      default: "/dev/urandom"
      private: no

    - name: "auto_provision_dns_api_host"
      prompt: "Auto-provision DNS API hostname"
      default: "rest.easydns.net"
      private: no

    - name: "auto_provision_dns_api_url"
      prompt: "Auto-provision DNS API URL"
      default: "https://rest.easydns.net/zones/records/add/wp.example.com/cname"
      private: no

    - name: "auto_provision_dns_api_username"
      prompt: "Auto-provision DNS API username"
      default: "default"
      private: no

    - name: "auto_provision_dns_api_password"
      prompt: "Auto-provision DNS API password"
      default: "default"
      private: yes

    - name: "auto_provision_console_api_key_secret"
      prompt: "Auto-provision Console API secret key"
      default: "default"
      private: yes

    - name: "auto_provision_gpg_id"
      prompt: "Email or keyID of GPG account for encrypting logs" 
      default: "sysops@equalit.ie"
      private: no

    - name: "auto_provision_ansible_version"
      prompt: "Version of Ansible to checkout"
      default: "v1.7.2"
      private: no

    - name: "nginx_worker_processes"
      prompt: "Nginx worker processes"
      default: "2"
      private: no

    - name: "phpfpm_max_children"
      prompt: "PHP-FPM max children"
      default: "48"
      private: no

    - name: "phpfpm_start_servers"
      prompt: "PHP-FPM start servers"
      default: "16"
      private: no

    - name: "phpfpm_min_spare"
      prompt: "PHP-FPM min spare"
      default: "16"
      private: no

    - name: "phpfpm_max_spare"
      prompt: "PHP-FPM max spare"
      default: "16"
      private: no

    - name: "phpfpm_max_requests"
      prompt: "PHP-FPM max requests"
      default: "32"
      private: no

    - name: "php_opcache_memory_size"
      prompt: "PHP-FPM opcache memory size"
      default: "128"
      private: no

    - name: "mysql_root_db_pass"
      prompt: "MySQL root user password"
      default: "enter_password"
      private: yes

    - name: "mysql_innodb_buffer_pool_size"
      prompt: "MySQL InnoDB buffer pool size"
      default: "256M"
      private: no

    - name: "mysql_innodb_log_file_size"
      prompt: "MySQL InnoDB log file size"
      default: "32M"
      private: no

  roles:
     - init-auto-provision

