---
- hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: "auto_provision_db_host"
      prompt: "Auto-provision database host"
      default: "localhost"
      private: no
    
    - name: "auto_provision_base_directory"
      prompt: "Auto-provision base directory"
      default: "/var/www/easypress.ca/provision"
      private: no

    - name: "auto_provision_log_file"
      prompt: "Auto-provision log file name (relative to base directory)"
      default: "ep-provision.log"
      private: no

    - name: "auto_provision_db_charset"
      prompt: "Auto-provision default database character set"
      default: "utf8"
      private: no

    - name: "auto_provision_db_collate"
      prompt: "Auto-provision default database collation"
      default: "utf8_unicode_ci"
      private: no

    - name: "auto_provision_dev_rand"
      prompt: "Auto-provison random number device"
      default: "/dev/urandom"
      private: no

    - name: "auto_provision_dns_api_host"
      prompt: "Auto-provision DNS API hostname"
      default: "rest.easydns.net"
      private: no

    - name: "auto_provision_dns_api_url"
      prompt: "Auto-provision DNS API URL"
      default: "https://rest.easydns.net/zones/records/add/wp.example.com/cname"
      private: no

    - name: "auto_provision_dns_api_username"
      prompt: "Auto-provision DNS API username"
      default: "default"
      private: no

    - name: "auto_provision_dns_api_username"
      prompt: "Auto-provision DNS API username"
      default: "default"
      private: no

    - name: "auto_provision_console_api_key_secret"
      prompt: "Auto-provision Console API secret key"
      default: "default"
      private: yes

    - name: "auto_provision_gpg_id"
      prompt: "Email or keyID of GPG account for encrypting logs" 
      default: "sysops@equalit.ie"
      private: no

    - name: "auto_provision_ansible_version"
      prompt: "Version of Ansible to checkout"
      default: "1.8"
      private: no

  roles:
     - init-auto-provision
