---
- hosts: all
  gather_facts: true
  roles:
     - common
     - ssh-config
     - easypress-ssl
     - web-app
     - easypress-console
     - easypress-devops
     - mysql-percona-replication
     - mysql-enable-replication

#  tasks:
#    - name: reboot
#      command: reboot
