---
# file: roles/provision-testing/tasks/main.yml

- name: deploy provision scripts
  local_action: command rsync -vrlD {{ files }}/var/www/{{ auto_provision_base_directory }}/provision/ {{ ansible_ssh_user }}@{{ inventory_hostname }}:/var/www/{{ auto_provision_base_directory }}/provision-testing
  tags: provision-testing

- name: deploy monit script
  copy: src={{ files }}/usr/local/sbin/monit_ep_provision_testing.sh dest=/usr/local/sbin mode=0750 owner=root group=staff
  tags: provision-testing

- name: deploy ansible hosts file
  copy: src={{ files }}/etc/ansible/hosts dest=/etc/ansible mode=0644 owner=root group=staff
  tags: provision-testing
