---
# defaults file for timezone
timezone: "America/Toronto"
reboot_after_install: "no"
locale_lang: "en_CA.UTF-8"
bashrc_proxy_ftp: ""
bashrc_proxy_http: ""
mail_service: 'mandrill'
email_domain: 'example.co'
