---
# roles/init-env/tasks/main.yml

- name: Create group_vars directory.
  local_action:
    module: file
    path: "{{ playbook_dir }}/group_vars"
    state: directory
    mode: '0755'

- name: Create host_vars directory.
  local_action:
    module: file
    path: "{{ playbook_dir }}/host_vars"
    state: directory
    mode: '0755'

- name: Create the main variables file (group_vars/all.yml).
  local_action:
    module: template
    src: all.yml.j2
    dest: "group_vars/all.yml"

- name: Load main variables file for next tasks
  include_vars: "group_vars/all.yml"
