---
# file: roles/deploy-auto-provision-code-testing/tasks/main.yml

- name: deploy provision scripts
  local_action: command rsync -vrlD {{ files }}{{ auto_provision_base_directory }}/ root@{{ inventory_hostname }}:{{ auto_provision_base_directory }}/provision-testing/
  tags: provision-testing

- name: deploy main code from template
  template: src={{ files }}{{ auto_provision_base_directory }}/ep-provision.php.j2 dest={{ auto_provision_base_directory }}-testing/ep-provision.php mode=0644 owner=www-data group=www-data

- name: deploy util code from template
  template: src={{ files }}{{ auto_provision_base_directory }}/includes/class-ep-provision-util.php.j2 dest={{ auto_provision_base_directory }}/includes/class-ep-provision-util.php mode=0644 owner=www-data group=www-data

- name: deploy monit script
  template: src={{ files }}/usr/local/sbin/monit_ep_provision_testing.sh.j2 dest=/usr/local/sbin/monit_ep_provision_testing.sh mode=0750 owner=root group=staff
  tags: provision-testing

- name: deploy ansible hosts file
  template: src={{ files }}/etc/ansible/hosts.j2 dest=/etc/ansible/hosts mode=0644 owner=root group=staff
  tags: provision-testing

