---
# roles/gen-root-cert/tasks/main.yml

- name: create {{ ssl_dir }}
  local_action:
    module: file
    path: "{{ ssl_dir }}"
    state: directory
    mode: '0750'
  run_once: yes
  tags:
    - ssl

- name: Generate openssl configuration.
  local_action:
    module: template
    src: genRootCA.conf.j2
    dest: "{{ ssl_dir }}/genRootCA.conf"
    mode: '0644'
  run_once: yes
  tags:
    - ssl

- name: install genRootCA.sh to config
  local_action:
    module: template
    src: genRootCA.sh.j2
    dest: "{{ ssl_dir }}/genRootCA.sh"
    mode: '0755'
  run_once: yes
  tags:
    - ssl

- name: Generate root certificate.
  local_action:
    module: command ./genRootCA.sh
    args:
      chdir: "{{ ssl_dir }}"
      creates: root_CA.key
  run_once: yes
  tags:
    - ssl
