---
# roles/easypress-console/tasks/main.yml
# FIXME: these perms can prob be root:root for all /var/www/....
#
- name: copy console install script
  template:
    src: "{{ files }}/usr/local/sbin/ep_install_console.sh.j2"
    dest: /usr/local/sbin
    owner: root
    group: staff
    mode: '0755'
  tags:
    - ep-console
    - ep_install_console.sh

- name: copy console monit scripts
  template:
    src: "{{ files }}/usr/local/sbin/{{item}}.j2"
    dest: "/usr/local/sbin/{{item}}"
    owner: root
    group: staff
    mode: '0755'
  loop:
    - monit_ep_console_lockdown.sh
    - monit_ep_console_perms.sh
    - monit_connections.sh
  tags:
    - ep-console
    - console_monit_scripts
    - monit

- name: copy console-related templates
  template:
    src: "{{ files }}/usr/local/sbin/{{ item }}.j2"
    dest: "/usr/local/sbin/{{ item }}"
    owner: root
    group: staff
    mode: '0755'
  loop:
    - monit_ep_console_reset_password.sh
    - nagios_check_mysql.php
  tags:
    - ep-sbin
    - ep-sbin-templates
    - monitoring

- name: ensure /var/www exists and is owned by root
  file:
    path: /var/www
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - var-www-root

- name: create eqpress docroot "{{ eqpress_docroot }}"
  file:
    path: "{{ eqpress_docroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  tags:
    - ep-console

- name: create eqpress .sesssions directory for PHP sessions and adminer to work
  file:
    path: "{{ eqpress_docroot }}/.sessions"
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
  tags:
    - ep-console

- name: make webstats directory
  file:
    path: "{{ eqpress_docroot }}/webstats"
    owner: root
    group: root
    mode: '0755'
    state: directory
  tags:
    - ep-console
    - webstats

- name: create the console directories
  file:
    path: "{{ eqpress_docroot }}/console/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
  loop:
    - lockdown
    - lockdown/lock
    - lockdown/unlock
    - log
    - password
    - perms
    - proxy
  tags:
    - ep-console

- name: copy eqpress-console-proxy.php from template
  template:
    src: "{{ files }}/var/www/eqpress-www/console/proxy/eqpress-console-proxy.php.j2"
    dest: "{{ eqpress_docroot }}/console/proxy/eqpress-console-proxy.php"
    owner: root
    group: www-data
    mode: '0644'
  tags:
    - ep-console
    - ep-console-proxy-code

- name: create catchall directory
  file:
    path: "{{ eqpress_docroot }}/catchall"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  tags:
    - ep-console
    - catchall

- name: copy catchall index
  template:
    src: "{{ files }}{{ eqpress_docroot }}/catchall/index.html.j2"
    dest: "{{ eqpress_docroot }}/catchall/index.html"
    owner: www-data
    group: www-data
    mode: '0664'
  tags:
    - ep-console
    - catchall

- name: create mrtg directory
  file:
    path: "{{ eqpress_docroot }}/mrtg"
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
  tags:
    - ep-console
    - mrtg

- name: set ownership on eqpress docroot
  file:
    path: "{{ eqpress_docroot }}"
    owner: www-data
    group: www-data
    state: directory
  tags:
    - ep-console

- name: copy eqpress nginx config
  template:
    src: "{{ files }}/etc/nginx/sites-available/eqpress-www.j2"
    dest: /etc/nginx/sites-available/eqpress-www
    owner: root
    group: staff
    mode: '0664'
  notify:
     - reload nginx
  tags:
    - ep-console

- name: link eqpress-www nginx config
  file:
    src: /etc/nginx/sites-available/eqpress-www
    dest: /etc/nginx/sites-enabled/eqpress-www
    state: link
  tags:
    - ep-console

- name: synchronize eqpress Console files
  synchronize:
    src: "{{ files }}/var/www/eqpress-www/console/"
    dest: "{{ eqpress_docroot }}/console/"
    mode: push
    checksum: true
    rsync_opts:
      - '--exclude=*.j2'
      - '--chown=www-data:www-data'
  tags:
    - ep-console
    - console

- name: synchronize brutprotect files
  synchronize:
    src: "{{ files }}/var/www/eqpress-www/bruteprotect"
    dest: "{{ eqpress_docroot }}/"
    mode: push
    checksum: true
    rsync_opts:
      - '--exclude=*.j2'
      - '--chown=www-data:www-data'
  tags:
    - ep-console
    - bruteprotect

- name: synchronize adminer files
  synchronize:
    src: "{{ files }}/var/www/eqpress-www/adminer"
    dest: "{{ eqpress_docroot }}/"
    mode: push
    checksum: true
    rsync_opts:
      - '--exclude=*.j2'
      - '--chown=www-data:www-data'
  tags:
    - ep-console
    - adminer

- name: synchronize nginx-helper (cache purge) files
  synchronize:
    src: "{{ files }}/var/www/eqpress-www/cache-purge"
    dest: "{{ eqpress_docroot }}/"
    mode: push
    checksum: true
    rsync_opts:
      - '--exclude=*.j2'
      - '--chown=www-data:www-data'
  tags:
    - ep-console
    - cache-purge

- name: synchronize performance monitoring files
  synchronize:
    src: "{{ files }}/var/www/eqpress-www/perf"
    dest: "{{ eqpress_docroot }}/"
    mode: push
    checksum: true
    rsync_opts:
      - '--exclude=*.j2'
      - '--chown=www-data:www-data'
  tags:
    - ep-console
    - perf
