---
# roles/install-ansible/tasks/main.yml

- name: ensure the provision directory exists
  file: state=directory path={{ auto_provision_base_directory }} wner=www-data group=www-data mode=0775
  when: auto_provision_host
  tags: auto-provision

- name: clone the ansible repository
  git: repo=git://github.com/ansible/ansible.git
       dest={{ auto_provision_base_directory }}
       recursive=yes
       version={{ auto_provision_ansible_version }}
  when: auto_provision_host
  tags: auto-provision

