---
- hosts: all
  gather_facts: true

  vars:
    users:
    - name: root
      authorized:
        - "{{ files }}/authorized_keys/api"

  tasks:
  - name: Copy authorized_keys
    authorized_key: user={{ item.0.name }} key="{{ lookup('file', item.1) }}"
    with_subelements:
     - users
     - authorized

